on:
  push:
    tags:
      - "*"

jobs:
  print:    
    name: Print event
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
      - uses: actions/checkout@v2
      - name: "Fetch tag info"
        run: |
          git fetch --tags --force # Retrieve annotated tags.
          git branch --contains tags/$GITHUB_REF_NAME
